In [1]:
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 18 21:06:16 2017

@author: r.ali
"""

import pandas
import numpy as np
import matplotlib.pyplot as plt

 

df=pandas.read_csv("D:/DIH/Assignment Material/Updated Dataset/Dataset/chronic_kidney_disease_updated.csv")

#print column names
print(list(df) )

#print first 5 rows
print(df.head())

df.drop(df.index[[0]], inplace=True)
#df.drop('Unnamed: 0', axis=1, inplace=True)

print(df.dm.unique() )

def replace(tup, df):
    for i in tup:
        df.replace(to_replace=i, value=np.nan, inplace=True)
        
def cleandf(df):
   df=df.applymap(lambda x: str(x).strip())
   return df
    
df=cleandf(df)
    
replace(( "\t", " ", "?"), df)

print(df.dm.unique() )

numeric_columns= ['age', 'bp', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc']
for i in numeric_columns:
   df[i] = pandas.to_numeric(df[i], errors='coerce')

df.dtypes

print(df[['pc','al']])


df.rename(columns={'class': 'Class'}, inplace=True)
ckd=df[df.Class=='ckd']

normal_count=(len(ckd[ckd.rbc=='normal'].index))
abnormal_count=(len(ckd[ckd.rbc=='abnormal'].index))

ckd['rbc'].value_counts().plot(kind='bar')

print(ckd['bp'].max())


df.to_csv(path_or_buf="D:/DIH/Assignment Material/Updated Dataset/Dataset/chronic_kidney_disease_updated1.csv")

['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wbcc', 'rbcc', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class']
   age   bp     sg   al   su     rbc        pc         pcc          ba  bgr  \
0  NaN  NaN    NaN  NaN  NaN     NaN       NaN         NaN         NaN  NaN
1   48   80  1.020    1    0       ?    normal  notpresent  notpresent  121
2    7   50  1.020    4    0       ?    normal  notpresent  notpresent    ?
3   62   80  1.010    2    3  normal    normal  notpresent  notpresent  423
4   48   70  1.005    4    0  normal  abnormal     present  notpresent  117

   ...   pcv  wbcc rbcc  htn   dm  cad appet   pe  ane class
0  ...   NaN   NaN  NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN
1  ...    44  7800  5.2  yes  yes   no  good   no   no   ckd
2  ...    38  6000    ?   no   no   no  good   no   no   ckd
3  ...    31  7500    ?   no  yes   no  poor   no  yes   ckd
4  ...    32  6700  3.9  yes   no   no  poor  yes  yes   ckd

[5 rows x 25 columns]
['yes' 'no' ' yes' '\tno' '\tyes' '?']
['yes' 'no' nan]
           pc   al
1      normal    1
2      normal    4
3      normal    2
4    abnormal    4
5      normal    2
6         NaN    3
7      normal    0
8    abnormal    2
9    abnormal    3
10   abnormal    2
11   abnormal    2
12   abnormal    3
13     normal    3
14        NaN  NaN
15   abnormal    3
16     normal    3
17     normal    2
18        NaN  NaN
19     normal    0
20   abnormal    1
21   abnormal    2
22        NaN  NaN
23   abnormal    4
24     normal    0
25   abnormal    4
26     normal    0
27     normal    0
28   abnormal    3
29        NaN    1
30   abnormal    1
..        ...  ...
371    normal    0
372    normal    0
373    normal    0
374    normal    0
375    normal    0
376    normal    0
377    normal    0
378    normal    0
379    normal    0
380    normal    0
381    normal    0
382       NaN    0
383    normal    0
384    normal    0
385    normal    0
386    normal    0
387    normal    0
388    normal    0
389    normal    0
390    normal    0
391    normal    0
392    normal    0
393    normal    0
394    normal    0
395    normal    0
396    normal    0
397    normal    0
398    normal    0
399    normal    0
400    normal    0

[400 rows x 2 columns]
180.0